'use strict';
const $ = id => document.getElementById(id);
let selectedFile = null, uploading = false, available = false, snapshot = '', selectedJob = null;
const labels = {queued:'Queued',preparing:'Preparing audio',transcribing:'Transcribing',completed:'Ready',failed:'Failed',interrupted:'Interrupted'};
function node(tag, text, cls) { const e = document.createElement(tag); if (text != null) e.textContent = text; if (cls) e.className = cls; return e; }
function clock(seconds) { seconds = Math.max(0, Math.floor(seconds || 0)); return [Math.floor(seconds / 3600), Math.floor(seconds / 60) % 60, seconds % 60].map(x => String(x).padStart(2, '0')).join(':'); }
function choose(file) { if (uploading || !file) return; selectedFile = file; $('file-label').textContent = file.name; $('file-detail').textContent = (file.size / 1024 / 1024).toFixed(1) + ' MB · ready to upload'; $('submit').disabled = !available; $('upload-error').hidden = true; }
$('file').addEventListener('change', () => choose($('file').files[0]));
for (const event of ['dragover','dragleave','drop']) $('dropzone').addEventListener(event, e => { e.preventDefault(); $('dropzone').classList.toggle('drag', event === 'dragover'); if (event === 'drop') choose(e.dataTransfer.files[0]); });
async function api(path) { const res = await fetch(path); const data = await res.json(); if (!res.ok) throw new Error(data.detail || 'The server could not complete this request.'); return data; }
function downloads(job, compact = false) { const box = node('div', null, 'downloads'); for (const [ext,label] of compact ? [['docx','Word ↓']] : [['docx','Word ↓'],['txt','Text ↓'],['srt','Subtitles ↓'],['md','Markdown ↓'],['json','JSON ↓']]) { const a=node('a',label,'download'); a.href=`/api/jobs/${job.id}/download/${ext}`; a.download=`${job.title}.${ext}`; a.onclick=async event=>{event.preventDefault();if(a.getAttribute('aria-busy')==='true')return;a.setAttribute('aria-busy','true');a.textContent='Downloading…';try{const res=await fetch(a.href);if(!res.ok){const error=await res.json();throw new Error(error.detail||'Download failed');}const url=URL.createObjectURL(await res.blob());const save=node('a');save.href=url;save.download=a.download;document.body.append(save);save.click();save.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);a.textContent=label;a.removeAttribute('title');}catch(error){a.textContent='Download failed · retry';a.title=error.message;}finally{a.removeAttribute('aria-busy');}}; box.append(a); } return box; }
function card(job) { const box=node('article',null,'job'); box.dataset.jobId=job.id; const top=node('div',null,'job-top'); top.append(node('h3',job.title),node('span',labels[job.status] || job.status,'badge '+(job.complete?'':job.error?'failed':'active'))); box.append(top); const date=job.submitted_at ? new Date(job.submitted_at*1000).toLocaleDateString(undefined,{month:'short',day:'numeric'}) : ''; box.append(node('p',[date,job.duration_seconds?clock(job.duration_seconds):null,job.language==='auto'?'Language: auto':job.language.toUpperCase()].filter(Boolean).join(' · '),'meta'));
  if (['preparing','transcribing','queued'].includes(job.status)) { const row=node('div',null,'progress-label'); row.append(node('span',job.status==='queued'?'Waiting for the worker':`${clock(job.processed_seconds)} of ${clock(job.duration_seconds)} processed`),node('span',`${job.progress}%`)); const bar=node('progress'); bar.max=100; bar.value=job.progress; bar.setAttribute('aria-label','Transcription progress'); box.append(row,bar); if(job.status!=='queued') box.append(node('p',`${clock(job.elapsed_seconds)} elapsed · updates automatically`,'meta')); }
  if(job.error) box.append(node('p',job.error,'error'));
  if(job.complete) { const actions=node('div',null,'job-actions'), read=node('button','Read transcript →','secondary read'); read.onclick=()=>openReader(job); actions.append(read); const dl=downloads(job,true); for(const a of [...dl.children]) actions.append(a); box.append(actions); } return box; }
async function refresh() { try { const data=await api('/api/jobs'); available=true; $('connection').className='connection'; $('connection').textContent=data.worker==='offline'?'Worker is offline. Uploads will wait until it restarts.':data.worker==='busy'?'● Server connected · processing a recording':'● Server connected · ready for a recording'; const next=JSON.stringify(data.jobs); if(next!==snapshot){ snapshot=next; $('jobs').replaceChildren(...data.jobs.map(card)); if(!data.jobs.length) $('jobs').append(node('p','Your recordings will appear here. Upload your first file to get started.','empty')); $('job-count').textContent=data.jobs.length; } } catch(e){ available=false; $('connection').className='connection bad'; $('connection').textContent=e.message==='Failed to fetch'?'Connection lost. Reconnecting automatically…':e.message; } $('submit').disabled=uploading||!available||!selectedFile; }
$('upload-form').addEventListener('submit', e => { e.preventDefault(); if(!selectedFile||uploading)return; if(selectedFile.size>2*1024**3){$('upload-error').textContent='Files can be up to 2 GB.';$('upload-error').hidden=false;return;} uploading=true; $('submit').disabled=true; $('file').disabled=true; $('upload-error').hidden=true; $('upload-progress').hidden=false; $('upload-bar').value=0; $('upload-message').textContent='Uploading to your server'; $('upload-percent').textContent='0%'; const params=new URLSearchParams({filename:selectedFile.name,title:$('title').value,language:$('language').value}); const xhr=new XMLHttpRequest(); xhr.open('POST','/api/jobs?'+params); xhr.setRequestHeader('X-Transcriber-Request','1'); xhr.setRequestHeader('Content-Type','application/octet-stream'); xhr.upload.onprogress=event=>{if(event.lengthComputable){const percent=Math.round(event.loaded/event.total*100);$('upload-bar').value=percent;$('upload-percent').textContent=percent+'%';if(percent===100)$('upload-message').textContent='Checking the audio track…';}};
  const finish=error=>{uploading=false;$('file').disabled=false;if(error){$('upload-error').textContent=error;$('upload-error').hidden=false;$('upload-progress').hidden=true;}refresh();};
  xhr.onload=()=>{let data;try{data=JSON.parse(xhr.responseText);}catch{finish('Upload failed. Please try again.');return;}if(xhr.status!==202){finish(data.detail||'Upload failed.');return;}$('upload-message').textContent='Uploaded · added to your library';$('upload-bar').value=100;$('upload-percent').textContent='✓';selectedFile=null;$('file').value='';$('title').value='';$('file-label').textContent='Choose another recording';$('file-detail').textContent='or drop your audio or video here';finish();}; xhr.onerror=()=>finish('Upload connection lost. Check your connection and try again.');xhr.send(selectedFile);
});
async function openReader(job){selectedJob=job.id;$('reader-title').textContent=job.title;$('reader-downloads').replaceChildren(...downloads(job).children);$('reader-content').replaceChildren(node('p','Loading transcript…','meta'));$('reader').showModal();try{const data=await api(`/api/jobs/${job.id}/transcript`);if(selectedJob!==job.id)return;const groups=[];for(const seg of data.segments){let group=groups[groups.length-1];if(!group||seg.end-group.start>60||group.text.length>850){group={start:seg.start,text:''};groups.push(group);}group.text+=seg.text;} $('reader-content').replaceChildren(...groups.map(group=>{const row=node('div',null,'transcript-paragraph');row.append(node('span',clock(group.start),'timestamp'),node('p',group.text.trim()));return row;}));if(!groups.length)$('reader-content').append(node('p','No speech was detected.'));}catch(e){$('reader-content').replaceChildren(node('p',e.message,'error'));}}
$('close-reader').onclick=()=>{$('reader').close();selectedJob=null;};
window.addEventListener('beforeunload',event=>{if(uploading){event.preventDefault();event.returnValue='';}});
refresh();setInterval(refresh,2500);
